### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Droppers** [zainulhassan815/animated-tab-bar#1]
In what way does this differ from my repository, looks like you literally just cloned my repo?

**Comment by zainulhassan815** [comment]
I know its almost same but if you look closely at the code, it is meant to be used in AppInventor and it's distros. Often UI related libraries (and sometimes non-ui libraries as well) don't work in such no code app builders. I have used your library and made it compatible with AppInventor and distros. So its not literally same. You can view the code if you want yourself.
